name: New Pull Request
description: Open a new pull request
body:
  - type: input
    id: related_issue
    attributes:
      label: Related Issue(s)
      description: Github issue related to the pull request
      placeholder: Resolves  
    validations:
      required: true
  - type: input
    id: related_pr
    attributes:
      label: Related PR(s)
      description: Other PRs related to the pull request
      value: "N/A"
    validations:
      required: false 
  - type: textarea
    id: approach
    attributes:
      label: Approach/Solution
      description: Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
    validations:
      required: true
  - type: textarea
    id: releaseNote
    attributes:
      label: Release Note
      description: Brief description of the new feature or bug fix as it will appear in the release notes
    validations:
      required: true
