name: New Pull Request
description: Open a new pull request
#title: "[Bug]: "
#labels: ["bug", "triage"]

body:
  - type: input
    id: related_issue
    attributes:
      label: Related Issue(s)
      description: Github issue related to the pull request
      placeholder: Resolves  
    validations:
      required: true
  - type: input
    id: related_pr
    attributes:
      label: Related PR(s)
      description: Other PRs related to the pull request
      value: "N/A"
    validations:
      required: false 
  - type: textarea
    id: approach
    attributes:
      label: Approach/Solution
      description: Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
    validations:
      required: true
  - type: textarea
    id: releaseNote
    attributes:
      label: Release Note
      description: Brief description of the new feature or bug fix as it will appear in the release notes
    validations:
      required: true
  
  
  - type: input
    id: related_docs
    attributes:
      label: Related Documentation
      description: Link(s) to product documentation that addresses the changes of this PR. 
      value: "N/A"
    validations:
      required: false 
  - type: checkboxes
    id: validity_checks
    attributes:
      label: PR Validation
      description: Before submitting PR for a new connector make sure following is completed
      options:
        - label: Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
          required: true
  - type: checkboxes
    id: security_checks
    attributes:
      label: Security Checks
      description: Before submitting PR make sure following security checks are followed
      options:
        - label: Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
          required: true
        - label: Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?
          required: true
  - type: textarea
    id: testEnv
    attributes:
      label: Test Environments
      description: BList all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
    validations:
      required: false      
        
